import uuid
from sqlalchemy.orm import Session
from app.models.certification import Certification, CertificationSkill
from app.models.question import Question, QuestionOption


def seed_database(db: Session):
    if db.query(Certification).count() > 0:
        return

    certs = [
        {"code": "AZ-900", "name": "Microsoft Azure Fundamentals", "description": "Foundational knowledge of cloud services and Microsoft Azure.", "level": "Fundamentals", "exam_url": "https://learn.microsoft.com/en-us/certifications/exams/az-900"},
        {"code": "AZ-104", "name": "Microsoft Azure Administrator", "description": "Implement, manage, and monitor an organization's Azure environment.", "level": "Associate", "exam_url": "https://learn.microsoft.com/en-us/certifications/exams/az-104"},
        {"code": "AI-102", "name": "Designing and Implementing Azure AI Solutions", "description": "Build AI apps and agents using Azure AI services.", "level": "Associate", "exam_url": "https://learn.microsoft.com/en-us/certifications/exams/ai-102"},
        {"code": "AB-100", "name": "Agile Business Fundamentals", "description": "Core principles of Agile delivery, Scrum, Kanban, and iterative project management.", "level": "Fundamentals", "exam_url": ""},
        {"code": "GH-300", "name": "GitHub Advanced Developer", "description": "Advanced GitHub workflows, Actions, Packages, Codespaces, and enterprise administration.", "level": "Advanced", "exam_url": ""},
        {"code": "AI-103", "name": "Applied AI Engineering", "description": "Design and deploy production-grade AI systems using modern LLMs, RAG, and MLOps practices.", "level": "Associate", "exam_url": ""},
    ]

    skills_map = {
        "AZ-900": ["Cloud Concepts", "Azure Architecture & Services", "Azure Management & Governance", "Security & Compliance", "Pricing & Support"],
        "AZ-104": ["Identity & Governance", "Storage", "Compute", "Networking", "Monitoring & Backup"],
        "AI-102": ["AI Workloads & Considerations", "Computer Vision", "Natural Language Processing", "Conversational AI", "Knowledge Mining"],
        "AB-100": ["Agile Principles", "Scrum Framework", "Kanban", "Backlog Management", "Agile Metrics"],
        "GH-300": ["GitHub Actions", "GitHub Packages & Codespaces", "Repository Management", "Security & Compliance", "GitHub Enterprise"],
        "AI-103": ["LLM Fundamentals", "Prompt Engineering", "RAG & Vector Databases", "MLOps & Deployment", "AI Safety & Ethics"],
    }

    # options are (text, is_correct)
    questions_seed = [
        # ── AZ-900 (20 questions) ─────────────────────────────────────────────
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Cloud Concepts",
         "text": "What is the primary benefit of cloud computing's economies of scale?",
         "explanation": "Cloud providers operate at massive scale, reducing per-unit costs and passing savings to customers.",
         "options": [("Lower variable costs compared to on-premises", True), ("Guaranteed 100% uptime", False), ("Unlimited free storage", False), ("Automatic deployment pipelines", False)]},
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Cloud Concepts",
         "text": "Which cloud service model gives the customer the most control over the underlying infrastructure?",
         "explanation": "IaaS provides virtualized compute, storage and networking — the customer manages OS, middleware and apps.",
         "options": [("IaaS", True), ("PaaS", False), ("SaaS", False), ("FaaS", False)]},
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Cloud Concepts",
         "text": "Which cloud deployment model keeps all resources on a company's own hardware?",
         "explanation": "A private cloud runs exclusively on an organization's own data-center infrastructure.",
         "options": [("Private cloud", True), ("Public cloud", False), ("Hybrid cloud", False), ("Community cloud", False)]},
        {"cert_code": "AZ-900", "difficulty": "Medium", "skill_area": "Cloud Concepts",
         "text": "What term describes the ability to quickly increase or decrease computing resources to meet demand?",
         "explanation": "Elasticity is the ability to automatically scale resources up or down based on demand.",
         "options": [("Elasticity", True), ("High availability", False), ("Fault tolerance", False), ("Disaster recovery", False)]},
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Cloud Concepts",
         "text": "In cloud computing, what does 'high availability' mean?",
         "explanation": "High availability ensures that a service remains accessible and operational for the maximum possible time.",
         "options": [("Maximum uptime and minimal service interruption", True), ("Fast data processing speed", False), ("Unlimited storage capacity", False), ("Free automatic backups", False)]},
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Azure Architecture & Services",
         "text": "What is an Azure Region?",
         "explanation": "An Azure Region is a set of datacenters deployed within a latency-defined perimeter connected through a low-latency network.",
         "options": [("A geographic area containing one or more datacenters", True), ("A single physical datacenter", False), ("A virtual network boundary", False), ("An availability set", False)]},
        {"cert_code": "AZ-900", "difficulty": "Medium", "skill_area": "Azure Architecture & Services",
         "text": "Which Azure storage service is best suited for storing unstructured binary data like images and videos?",
         "explanation": "Azure Blob Storage is optimized for storing massive amounts of unstructured object data.",
         "options": [("Azure Blob Storage", True), ("Azure File Storage", False), ("Azure Queue Storage", False), ("Azure Table Storage", False)]},
        {"cert_code": "AZ-900", "difficulty": "Medium", "skill_area": "Azure Architecture & Services",
         "text": "Which Azure service would you use to create a private network in Azure that resembles a traditional on-premises network?",
         "explanation": "Azure Virtual Network (VNet) is the fundamental building block for private networking in Azure.",
         "options": [("Azure Virtual Network", True), ("Azure ExpressRoute", False), ("Azure DNS", False), ("Azure Load Balancer", False)]},
        {"cert_code": "AZ-900", "difficulty": "Hard", "skill_area": "Azure Architecture & Services",
         "text": "What is the purpose of Azure Availability Zones?",
         "explanation": "Availability Zones are physically separate locations within a region that protect against datacenter failures.",
         "options": [("Protect from datacenter-level failures within a region", True), ("Replicate data across regions automatically", False), ("Provide global load balancing", False), ("Enable serverless computing", False)]},
        {"cert_code": "AZ-900", "difficulty": "Hard", "skill_area": "Azure Architecture & Services",
         "text": "Which Azure service enables you to run containerized applications without managing the underlying server infrastructure?",
         "explanation": "Azure Container Instances (ACI) is a serverless container runtime that requires no infrastructure management.",
         "options": [("Azure Container Instances", True), ("Azure Virtual Machines", False), ("Azure Kubernetes Service", False), ("Azure App Service", False)]},
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Azure Management & Governance",
         "text": "What is the purpose of Azure Resource Groups?",
         "explanation": "A resource group is a container that holds related resources for an Azure solution.",
         "options": [("Logical containers for grouping related Azure resources", True), ("Billing boundaries for Azure services", False), ("Security boundaries between tenants", False), ("Physical datacenter boundaries", False)]},
        {"cert_code": "AZ-900", "difficulty": "Medium", "skill_area": "Azure Management & Governance",
         "text": "Which Azure feature allows you to organize resources into logical groups that mirror your company's structure?",
         "explanation": "Management Groups allow you to manage access, policy, and compliance across multiple Azure subscriptions.",
         "options": [("Management Groups", True), ("Resource Groups", False), ("Subscriptions", False), ("Azure Policy", False)]},
        {"cert_code": "AZ-900", "difficulty": "Hard", "skill_area": "Azure Management & Governance",
         "text": "Which Azure tool provides recommendations to improve reliability, security, performance, and cost?",
         "explanation": "Azure Advisor analyzes your configurations and offers personalized, actionable recommendations.",
         "options": [("Azure Advisor", True), ("Azure Monitor", False), ("Azure Policy", False), ("Azure Blueprints", False)]},
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Security & Compliance",
         "text": "What security model assumes breach and verifies each request as though it originates from an open network?",
         "explanation": "Zero Trust is a security strategy that assumes breach and requires verification from everyone.",
         "options": [("Zero Trust", True), ("Defense in depth", False), ("Least privilege", False), ("Shared responsibility", False)]},
        {"cert_code": "AZ-900", "difficulty": "Medium", "skill_area": "Security & Compliance",
         "text": "Which Azure service provides centralized security policy management and threat protection across hybrid cloud workloads?",
         "explanation": "Microsoft Defender for Cloud provides unified security management and advanced threat protection.",
         "options": [("Microsoft Defender for Cloud", True), ("Azure Firewall", False), ("Azure DDoS Protection", False), ("Azure Sentinel", False)]},
        {"cert_code": "AZ-900", "difficulty": "Medium", "skill_area": "Security & Compliance",
         "text": "What Azure service provides multi-factor authentication and single sign-on for Azure resources?",
         "explanation": "Microsoft Entra ID (formerly Azure Active Directory) is Microsoft's cloud-based identity and access management service.",
         "options": [("Microsoft Entra ID (Azure Active Directory)", True), ("Azure Key Vault", False), ("Azure Firewall", False), ("Azure Bastion", False)]},
        {"cert_code": "AZ-900", "difficulty": "Medium", "skill_area": "Pricing & Support",
         "text": "What does the Azure SLA guarantee for a single-instance Virtual Machine using Premium SSD?",
         "explanation": "Microsoft guarantees 99.9% uptime for single VMs on Premium SSD storage.",
         "options": [("99.9%", True), ("99.99%", False), ("99.5%", False), ("100%", False)]},
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Pricing & Support",
         "text": "Which Azure tool helps estimate the monthly cost before deploying resources?",
         "explanation": "The Azure Pricing Calculator lets you configure expected resources and see estimated monthly costs.",
         "options": [("Azure Pricing Calculator", True), ("Azure Cost Management", False), ("Azure Advisor", False), ("Azure Monitor", False)]},
        {"cert_code": "AZ-900", "difficulty": "Medium", "skill_area": "Pricing & Support",
         "text": "Which Azure pricing option provides the greatest discount for predictable, long-term workloads?",
         "explanation": "Azure Reservations allow you to pre-pay for 1 or 3 years for significant discounts over pay-as-you-go.",
         "options": [("Azure Reservations (1 or 3 year)", True), ("Pay-as-you-go", False), ("Spot pricing", False), ("Dev/Test pricing", False)]},
        {"cert_code": "AZ-900", "difficulty": "Easy", "skill_area": "Azure Architecture & Services",
         "text": "Which Azure service provides a fully managed relational database with automatic scaling?",
         "explanation": "Azure SQL Database is a PaaS offering that handles patching, backups, and scaling automatically.",
         "options": [("Azure SQL Database", True), ("Azure Blob Storage", False), ("Azure Table Storage", False), ("Azure Data Lake", False)]},

        # ── AZ-104 (20 questions) ─────────────────────────────────────────────
        {"cert_code": "AZ-104", "difficulty": "Easy", "skill_area": "Identity & Governance",
         "text": "What scope is highest in the Azure management hierarchy?",
         "explanation": "Management Groups sit above Subscriptions, then Resource Groups, then individual Resources.",
         "options": [("Management Group", True), ("Subscription", False), ("Resource Group", False), ("Resource", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Identity & Governance",
         "text": "What is the minimum Azure RBAC role required to create and manage virtual machines?",
         "explanation": "The Virtual Machine Contributor role lets you manage VMs but not the VNet/storage they connect to.",
         "options": [("Virtual Machine Contributor", True), ("Owner", False), ("Reader", False), ("Contributor", False)]},
        {"cert_code": "AZ-104", "difficulty": "Easy", "skill_area": "Identity & Governance",
         "text": "Which Azure feature allows you to enforce organizational standards and assess compliance at scale?",
         "explanation": "Azure Policy helps enforce organizational standards and assess compliance for resource consistency.",
         "options": [("Azure Policy", True), ("Azure RBAC", False), ("Azure Blueprints", False), ("Azure Monitor", False)]},
        {"cert_code": "AZ-104", "difficulty": "Hard", "skill_area": "Identity & Governance",
         "text": "What is Privileged Identity Management (PIM) used for in Azure?",
         "explanation": "PIM provides time-based and approval-based role activation to mitigate excessive or unnecessary access.",
         "options": [("Just-in-time privileged access with approval workflows", True), ("Permanent admin role assignments", False), ("MFA enforcement", False), ("Resource lock management", False)]},
        {"cert_code": "AZ-104", "difficulty": "Hard", "skill_area": "Identity & Governance",
         "text": "What is a Managed Identity in Azure?",
         "explanation": "A Managed Identity provides an automatically managed identity in Microsoft Entra ID, eliminating the need to store credentials in code.",
         "options": [("An automatically managed service principal with no credentials to manage", True), ("A VM administrator account", False), ("An encryption key in Key Vault", False), ("An Azure AD B2C user account", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Storage",
         "text": "Which Azure storage redundancy option replicates data synchronously across three availability zones in the same region?",
         "explanation": "Zone-Redundant Storage (ZRS) replicates data synchronously across three availability zones.",
         "options": [("Zone-Redundant Storage (ZRS)", True), ("Locally Redundant Storage (LRS)", False), ("Geo-Redundant Storage (GRS)", False), ("Read-Access Geo-Redundant Storage (RA-GRS)", False)]},
        {"cert_code": "AZ-104", "difficulty": "Easy", "skill_area": "Storage",
         "text": "Which tool can you use to transfer large amounts of data to Azure Blob Storage when bandwidth is limited?",
         "explanation": "AzCopy is a command-line tool for copying data to/from Azure storage efficiently, supporting resumable transfers.",
         "options": [("AzCopy", True), ("Azure Data Factory", False), ("Azure Import/Export service", False), ("Azure Storage Explorer (GUI only)", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Storage",
         "text": "Which Azure Blob Storage access tier is most cost-effective for data accessed less than once a month?",
         "explanation": "Archive tier has the lowest storage cost but highest access cost, suitable for rarely accessed compliance data.",
         "options": [("Archive", True), ("Cool", False), ("Hot", False), ("Premium", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Compute",
         "text": "What is the purpose of an Azure Virtual Machine Scale Set?",
         "explanation": "VM Scale Sets let you create and manage a group of load-balanced VMs that auto-scale based on demand.",
         "options": [("Automatically scale VM capacity based on load", True), ("Provide static IP addresses for VMs", False), ("Enable disk encryption on VMs", False), ("Back up VMs to a Recovery Services vault", False)]},
        {"cert_code": "AZ-104", "difficulty": "Hard", "skill_area": "Compute",
         "text": "Which Azure service allows you to run application code without provisioning or managing servers?",
         "explanation": "Azure Functions is a serverless compute service that runs event-triggered code without infrastructure management.",
         "options": [("Azure Functions", True), ("Azure Virtual Machines", False), ("Azure App Service", False), ("Azure Container Instances", False)]},
        {"cert_code": "AZ-104", "difficulty": "Hard", "skill_area": "Compute",
         "text": "What is the difference between Azure VM availability sets and availability zones?",
         "explanation": "Availability sets protect against rack/server failures within a single datacenter; availability zones protect against entire datacenter failures.",
         "options": [("Sets protect from rack failures; zones protect from datacenter failures", True), ("They are identical features with different names", False), ("Availability zones are only available in premium SKUs", False), ("Availability sets span multiple regions", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Networking",
         "text": "What does Azure Network Security Group (NSG) do?",
         "explanation": "NSGs contain security rules that allow or deny inbound/outbound network traffic based on 5-tuple information.",
         "options": [("Filters inbound and outbound network traffic using rules", True), ("Encrypts data in transit automatically", False), ("Provides DDoS protection", False), ("Routes traffic between virtual networks", False)]},
        {"cert_code": "AZ-104", "difficulty": "Hard", "skill_area": "Networking",
         "text": "What is the difference between Azure VNet Peering and VPN Gateway for connecting two VNets?",
         "explanation": "VNet Peering uses the Microsoft backbone (low latency, no public internet); VPN Gateway uses encrypted IPsec tunnels useful for cross-region or on-premises.",
         "options": [("Peering uses private backbone; VPN uses encrypted tunnels over internet", True), ("Peering is only for same-region VNets; VPN is cross-region only", False), ("VPN is always faster than peering", False), ("They are identical in functionality", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Networking",
         "text": "What is the purpose of Azure Load Balancer?",
         "explanation": "Azure Load Balancer distributes inbound traffic among healthy backend pool instances for high availability.",
         "options": [("Distribute inbound network traffic across multiple backend resources", True), ("Encrypt traffic between VNets", False), ("Monitor network performance", False), ("Assign public IP addresses to VMs", False)]},
        {"cert_code": "AZ-104", "difficulty": "Easy", "skill_area": "Monitoring & Backup",
         "text": "Which Azure service allows you to collect, analyze, and act on telemetry from cloud and on-premises environments?",
         "explanation": "Azure Monitor is the platform service for full-stack monitoring — metrics, logs, alerts, and dashboards.",
         "options": [("Azure Monitor", True), ("Azure Advisor", False), ("Azure Security Center", False), ("Azure Service Health", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Monitoring & Backup",
         "text": "What is the Recovery Time Objective (RTO)?",
         "explanation": "RTO is the maximum acceptable length of time that an application can be offline after a disaster.",
         "options": [("Maximum acceptable downtime after a failure", True), ("Maximum acceptable data loss in time", False), ("Time to replicate data to secondary region", False), ("Frequency of backup snapshots", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Monitoring & Backup",
         "text": "What is the Recovery Point Objective (RPO)?",
         "explanation": "RPO is the maximum acceptable amount of data loss measured in time — how far back data recovery can go.",
         "options": [("Maximum acceptable data loss measured in time", True), ("Maximum acceptable downtime after a failure", False), ("Time to restore a backup", False), ("Number of backup copies retained", False)]},
        {"cert_code": "AZ-104", "difficulty": "Hard", "skill_area": "Monitoring & Backup",
         "text": "Which Azure service enables you to query, analyze, and visualize log data from across Azure resources?",
         "explanation": "Azure Log Analytics (part of Azure Monitor) stores and queries log data using the Kusto Query Language (KQL).",
         "options": [("Azure Log Analytics (Azure Monitor Logs)", True), ("Azure Metrics Explorer", False), ("Azure Application Insights only", False), ("Azure Data Explorer", False)]},
        {"cert_code": "AZ-104", "difficulty": "Medium", "skill_area": "Identity & Governance",
         "text": "What is the purpose of Azure Resource Locks?",
         "explanation": "Resource Locks prevent accidental deletion or modification of Azure resources by applying CanNotDelete or ReadOnly locks.",
         "options": [("Prevent accidental deletion or modification of resources", True), ("Encrypt resources at rest", False), ("Restrict who can view resource properties", False), ("Apply cost limits to a resource", False)]},
        {"cert_code": "AZ-104", "difficulty": "Easy", "skill_area": "Networking",
         "text": "What is the default outbound connectivity behavior for Azure VMs without a public IP or NAT gateway?",
         "explanation": "Azure provides default outbound SNAT for VMs, but this is not SLA-backed and should not be relied on for production workloads.",
         "options": [("Default SNAT is provided but not SLA-backed", True), ("No outbound connectivity exists by default", False), ("All traffic routes through Azure Firewall by default", False), ("A public IP is automatically assigned", False)]},

        # ── AI-102 (20 questions) ─────────────────────────────────────────────
        {"cert_code": "AI-102", "difficulty": "Easy", "skill_area": "AI Workloads & Considerations",
         "text": "Which Azure service provides a unified set of REST APIs for building intelligent applications with pre-built AI models?",
         "explanation": "Azure AI Services (formerly Cognitive Services) provides REST APIs and SDKs for vision, speech, language, and decision capabilities.",
         "options": [("Azure AI Services (Cognitive Services)", True), ("Azure Machine Learning", False), ("Azure Databricks", False), ("Azure Synapse Analytics", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "AI Workloads & Considerations",
         "text": "What is responsible AI principle of 'Fairness' concerned with?",
         "explanation": "Fairness ensures that AI systems treat all people fairly and avoid affecting similarly situated groups differently.",
         "options": [("AI systems should treat all people equitably without bias", True), ("AI systems should be explainable to users", False), ("AI systems should be reliable and safe", False), ("AI systems should protect user privacy", False)]},
        {"cert_code": "AI-102", "difficulty": "Hard", "skill_area": "AI Workloads & Considerations",
         "text": "What does 'grounding' mean in the context of Azure OpenAI and generative AI?",
         "explanation": "Grounding means connecting the AI model to authoritative data sources so it generates responses based on verified, relevant information rather than hallucinating.",
         "options": [("Connecting the model to authoritative data to reduce hallucinations", True), ("Training the model on domain-specific data from scratch", False), ("Applying content filters to model output", False), ("Limiting the model's response length", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "Computer Vision",
         "text": "Which Azure AI service can analyze images and extract text, objects, and scene descriptions?",
         "explanation": "Azure AI Vision provides algorithms to process images and return visual feature information.",
         "options": [("Azure AI Vision", True), ("Azure AI Face", False), ("Azure AI Custom Vision", False), ("Azure AI Document Intelligence", False)]},
        {"cert_code": "AI-102", "difficulty": "Hard", "skill_area": "Computer Vision",
         "text": "What is the difference between Azure AI Vision and Azure AI Custom Vision?",
         "explanation": "Azure AI Vision uses pre-built general models; Custom Vision lets you train domain-specific image classification or object detection models with your own labeled data.",
         "options": [("Custom Vision lets you train domain-specific models with your own data", True), ("Custom Vision is only for video analysis", False), ("Azure AI Vision requires model training", False), ("They are the same service with different names", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "Computer Vision",
         "text": "What does OCR (Optical Character Recognition) do in Azure AI Vision?",
         "explanation": "OCR extracts printed and handwritten text from images and documents, returning it as machine-readable text.",
         "options": [("Extracts printed and handwritten text from images", True), ("Detects faces in photographs", False), ("Classifies image categories", False), ("Generates image captions", False)]},
        {"cert_code": "AI-102", "difficulty": "Easy", "skill_area": "Natural Language Processing",
         "text": "Which Azure AI service analyzes text for sentiment, key phrases, and named entities?",
         "explanation": "Azure AI Language (Text Analytics) provides NLP capabilities including sentiment analysis and entity recognition.",
         "options": [("Azure AI Language", True), ("Azure AI Translator", False), ("Azure AI Speech", False), ("Azure AI Bot Service", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "Natural Language Processing",
         "text": "Which service would you use to build a custom question-answering system from existing documents or FAQs?",
         "explanation": "Azure AI Language's Question Answering feature extracts Q&A pairs from semi-structured content like FAQ documents.",
         "options": [("Azure AI Language – Question Answering", True), ("Azure AI Search", False), ("Azure OpenAI Service", False), ("Azure Bot Service", False)]},
        {"cert_code": "AI-102", "difficulty": "Hard", "skill_area": "Natural Language Processing",
         "text": "What is the purpose of Named Entity Recognition (NER) in Azure AI Language?",
         "explanation": "NER identifies and classifies entities in text into predefined categories like people, places, organizations, dates, and quantities.",
         "options": [("Identify and classify entities like people, places, and organizations in text", True), ("Generate new text from a prompt", False), ("Translate text between languages", False), ("Summarize long documents automatically", False)]},
        {"cert_code": "AI-102", "difficulty": "Hard", "skill_area": "Conversational AI",
         "text": "What is the role of Azure Bot Service in a conversational AI solution?",
         "explanation": "Azure Bot Service provides hosting and channel integration, connecting bots to Teams, Web Chat, Slack, and more.",
         "options": [("Hosting and connecting chatbots to multiple communication channels", True), ("Training NLP models for intent recognition", False), ("Storing conversation history in a database", False), ("Generating text responses using a language model", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "Conversational AI",
         "text": "What does LUIS (Language Understanding Intelligent Service) do in a bot solution?",
         "explanation": "LUIS uses machine learning to extract intents and entities from user utterances.",
         "options": [("Classifies user intent and extracts entities from natural language", True), ("Synthesizes speech from text", False), ("Translates text between languages", False), ("Generates conversational responses", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "Conversational AI",
         "text": "What is the difference between CLU (Conversational Language Understanding) and LUIS?",
         "explanation": "CLU is the next-generation successor to LUIS, offering multilingual support and better integration with Azure AI Language.",
         "options": [("CLU is the modern successor to LUIS with multilingual support", True), ("LUIS supports more languages than CLU", False), ("They are the same service", False), ("CLU only works with Azure Bot Service", False)]},
        {"cert_code": "AI-102", "difficulty": "Hard", "skill_area": "Knowledge Mining",
         "text": "What is the purpose of Azure AI Search's 'skillset' in an indexing pipeline?",
         "explanation": "A skillset is a collection of AI enrichment skills that transform, extract, and enrich content during indexing.",
         "options": [("Apply AI enrichments like OCR and entity extraction during indexing", True), ("Define the search index schema", False), ("Configure relevance scoring", False), ("Set up synonyms for search queries", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "Knowledge Mining",
         "text": "Which Azure service would you use to extract structured data from forms and documents automatically?",
         "explanation": "Azure AI Document Intelligence (Form Recognizer) uses machine learning to extract text, key-value pairs, and tables from documents.",
         "options": [("Azure AI Document Intelligence", True), ("Azure AI Vision", False), ("Azure Blob Storage with OCR", False), ("Azure AI Language", False)]},
        {"cert_code": "AI-102", "difficulty": "Easy", "skill_area": "Knowledge Mining",
         "text": "What is Azure AI Search primarily used for?",
         "explanation": "Azure AI Search is a cloud search service with built-in AI capabilities for indexing and querying diverse content types.",
         "options": [("Full-text and semantic search over indexed content", True), ("Training custom machine learning models", False), ("Running SQL queries on documents", False), ("Storing large binary files", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "AI Workloads & Considerations",
         "text": "What is Azure OpenAI Service?",
         "explanation": "Azure OpenAI Service provides REST API access to OpenAI's language models including GPT-4, with Azure security and compliance.",
         "options": [("Managed access to OpenAI models with Azure security and compliance", True), ("An open-source AI framework from Microsoft", False), ("A visual model training studio", False), ("A replacement for Azure Machine Learning", False)]},
        {"cert_code": "AI-102", "difficulty": "Hard", "skill_area": "Computer Vision",
         "text": "What is 'spatial analysis' in Azure AI Vision?",
         "explanation": "Spatial analysis uses video to detect and analyze people's presence and movement in physical spaces, used for occupancy and safety scenarios.",
         "options": [("Analyzing people's presence and movement in physical spaces using video", True), ("3D mapping of outdoor environments", False), ("Detecting geographic coordinates in images", False), ("Rendering AR overlays on camera feeds", False)]},
        {"cert_code": "AI-102", "difficulty": "Easy", "skill_area": "Natural Language Processing",
         "text": "Which Azure AI service can translate text between more than 100 languages?",
         "explanation": "Azure AI Translator provides real-time text translation across 100+ languages using neural machine translation.",
         "options": [("Azure AI Translator", True), ("Azure AI Language", False), ("Azure AI Speech", False), ("Azure OpenAI Service", False)]},
        {"cert_code": "AI-102", "difficulty": "Medium", "skill_area": "Conversational AI",
         "text": "What is speech synthesis (text-to-speech) in Azure AI Speech?",
         "explanation": "Azure AI Speech's text-to-speech capability converts written text into natural-sounding spoken audio using neural voices.",
         "options": [("Converting written text into natural-sounding spoken audio", True), ("Transcribing audio to text", False), ("Detecting the language of spoken audio", False), ("Identifying the speaker from voice characteristics", False)]},
        {"cert_code": "AI-102", "difficulty": "Hard", "skill_area": "AI Workloads & Considerations",
         "text": "What is 'prompt flow' in Azure AI Foundry?",
         "explanation": "Prompt flow is a development tool for building, evaluating, and deploying LLM-based AI applications through visual workflow orchestration.",
         "options": [("A tool for building and deploying LLM-based AI application workflows", True), ("A monitoring dashboard for token usage", False), ("An API gateway for throttling AI requests", False), ("A data pipeline for training custom models", False)]},

        # ── AB-100 (20 questions) ─────────────────────────────────────────────
        {"cert_code": "AB-100", "difficulty": "Easy", "skill_area": "Agile Principles",
         "text": "According to the Agile Manifesto, what is valued more than processes and tools?",
         "explanation": "The Agile Manifesto states: 'Individuals and interactions over processes and tools.'",
         "options": [("Individuals and interactions", True), ("Comprehensive documentation", False), ("Contract negotiation", False), ("Following a plan", False)]},
        {"cert_code": "AB-100", "difficulty": "Easy", "skill_area": "Agile Principles",
         "text": "How often should working software be delivered according to Agile principles?",
         "explanation": "Agile principle 3: 'Deliver working software frequently, from a couple of weeks to a couple of months.'",
         "options": [("Frequently, from weeks to a few months", True), ("Once at the end of the project", False), ("Only after full requirements are documented", False), ("Annually on a fixed release schedule", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Agile Principles",
         "text": "What does the Agile principle 'Welcome changing requirements, even late in development' primarily support?",
         "explanation": "This principle acknowledges that business needs evolve and Agile processes harness change for competitive advantage.",
         "options": [("Customer competitive advantage through adaptability", True), ("Unlimited scope creep", False), ("Elimination of project planning", False), ("Replacing the product owner role", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Agile Principles",
         "text": "What is the recommended team size for a Scrum Development Team?",
         "explanation": "Scrum Guide recommends 10 or fewer Developers; typically 3–9 is ideal for cross-functional collaboration.",
         "options": [("Typically 10 or fewer people", True), ("Exactly 5 people", False), ("20 or more for large projects", False), ("No size constraint is specified", False)]},
        {"cert_code": "AB-100", "difficulty": "Easy", "skill_area": "Scrum Framework",
         "text": "What is the recommended maximum length of a Sprint in Scrum?",
         "explanation": "Scrum Guide: A Sprint is a fixed time-box of one month or less.",
         "options": [("One month", True), ("Six weeks", False), ("Three months", False), ("Two weeks only", False)]},
        {"cert_code": "AB-100", "difficulty": "Easy", "skill_area": "Scrum Framework",
         "text": "Who is responsible for maximizing the value of the product and managing the Product Backlog in Scrum?",
         "explanation": "The Product Owner is accountable for maximizing product value and is the sole person responsible for the Product Backlog.",
         "options": [("Product Owner", True), ("Scrum Master", False), ("Development Team", False), ("Stakeholders", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Scrum Framework",
         "text": "What is the purpose of the Daily Scrum (standup)?",
         "explanation": "The Daily Scrum is a 15-minute event for Developers to inspect progress and adapt the Sprint Backlog.",
         "options": [("Inspect progress toward Sprint Goal and adapt the plan", True), ("Report status to management", False), ("Assign tasks to team members", False), ("Discuss technical architecture decisions", False)]},
        {"cert_code": "AB-100", "difficulty": "Hard", "skill_area": "Scrum Framework",
         "text": "What is the 'Definition of Done' in Scrum?",
         "explanation": "The Definition of Done is a formal description of quality criteria an Increment must meet.",
         "options": [("A shared understanding of quality criteria an Increment must meet", True), ("A list of all user stories in a sprint", False), ("The acceptance criteria for a single story", False), ("The sprint planning checklist", False)]},
        {"cert_code": "AB-100", "difficulty": "Hard", "skill_area": "Scrum Framework",
         "text": "What is the Scrum Master's primary responsibility?",
         "explanation": "The Scrum Master is accountable for team effectiveness by coaching, removing impediments, and facilitating events.",
         "options": [("Serving the Scrum Team by coaching and removing impediments", True), ("Making all technical decisions for the team", False), ("Managing team performance reviews", False), ("Prioritizing the Product Backlog", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Scrum Framework",
         "text": "What happens during the Sprint Review?",
         "explanation": "The Sprint Review is held at the end of the Sprint to inspect the Increment and adapt the Product Backlog with stakeholders.",
         "options": [("The team demonstrates the Increment and gathers stakeholder feedback", True), ("The team reflects on their process and identifies improvements", False), ("The team commits to the next Sprint's backlog items", False), ("The Scrum Master reviews team velocity", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Kanban",
         "text": "What is the primary purpose of a WIP (Work In Progress) limit in Kanban?",
         "explanation": "WIP limits constrain concurrent work, reducing multitasking and improving flow.",
         "options": [("Reduce multitasking and improve flow by constraining concurrent work", True), ("Limit the team's capacity permanently", False), ("Prioritize the backlog items", False), ("Track velocity across sprints", False)]},
        {"cert_code": "AB-100", "difficulty": "Easy", "skill_area": "Kanban",
         "text": "What metric does Kanban use to measure the time from work item start to completion?",
         "explanation": "Cycle time measures elapsed time from when work starts on an item to when it is completed.",
         "options": [("Cycle time", True), ("Velocity", False), ("Story points", False), ("Burn-down rate", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Kanban",
         "text": "What is 'lead time' in Kanban?",
         "explanation": "Lead time is the total elapsed time from when a customer request is received (enters the backlog) to when it is delivered.",
         "options": [("Time from customer request to delivery", True), ("Time from work start to completion", False), ("Time spent in active development only", False), ("Time between sprint planning events", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Backlog Management",
         "text": "What is a User Story in Agile?",
         "explanation": "A User Story is a short feature description from the end user's perspective: 'As a [role], I want [goal], so that [benefit].'",
         "options": [("A feature description from the user's perspective", True), ("A detailed technical specification", False), ("A bug report from QA", False), ("A sprint planning document", False)]},
        {"cert_code": "AB-100", "difficulty": "Hard", "skill_area": "Backlog Management",
         "text": "What does INVEST stand for in the context of good user stories?",
         "explanation": "INVEST: Independent, Negotiable, Valuable, Estimable, Small, Testable — criteria for well-formed user stories.",
         "options": [("Independent, Negotiable, Valuable, Estimable, Small, Testable", True), ("Iterative, New, Verified, Estimated, Scoped, Tracked", False), ("Integrated, Nested, Validated, Executable, Sized, Tested", False), ("Important, Needed, Valued, Easy, Safe, Timely", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Backlog Management",
         "text": "What is 'backlog refinement' (grooming) in Agile?",
         "explanation": "Backlog refinement is the ongoing process of reviewing, prioritizing, and adding detail to backlog items to prepare them for future sprints.",
         "options": [("Reviewing and adding detail to backlog items to prepare for future sprints", True), ("Closing completed sprint backlog items", False), ("Moving items between sprints", False), ("Writing acceptance tests for completed stories", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Agile Metrics",
         "text": "What does 'velocity' measure in Scrum?",
         "explanation": "Velocity is the amount of work (story points) a team completes per Sprint, used for forecasting future sprints.",
         "options": [("The amount of work completed per Sprint", True), ("Number of bugs fixed per day", False), ("Team morale score", False), ("Number of meetings held per sprint", False)]},
        {"cert_code": "AB-100", "difficulty": "Easy", "skill_area": "Agile Metrics",
         "text": "What does a Sprint Burndown chart show?",
         "explanation": "A Sprint Burndown chart tracks remaining work (hours or story points) in the Sprint over time.",
         "options": [("Remaining work versus time remaining in the Sprint", True), ("Cumulative features delivered over the project", False), ("Team member utilization percentage", False), ("Number of user stories accepted per day", False)]},
        {"cert_code": "AB-100", "difficulty": "Hard", "skill_area": "Agile Metrics",
         "text": "What is a Release Burnup chart used for?",
         "explanation": "A Release Burnup chart tracks progress toward the total release scope over time, showing both completed work and scope changes.",
         "options": [("Track completed work and scope changes toward a release target", True), ("Show remaining Sprint work each day", False), ("Compare planned vs actual sprint velocity", False), ("Monitor individual team member contributions", False)]},
        {"cert_code": "AB-100", "difficulty": "Medium", "skill_area": "Scrum Framework",
         "text": "What is the Sprint Goal in Scrum?",
         "explanation": "The Sprint Goal is a single objective for the Sprint that provides focus and flexibility while allowing the team to deliver an Increment.",
         "options": [("A single objective that provides focus for the Sprint", True), ("A list of all stories committed for the Sprint", False), ("The team's performance target set by management", False), ("The deadline for the Sprint Review", False)]},

        # ── GH-300 (20 questions) ─────────────────────────────────────────────
        {"cert_code": "GH-300", "difficulty": "Easy", "skill_area": "GitHub Actions",
         "text": "What file format is used to define a GitHub Actions workflow?",
         "explanation": "GitHub Actions workflows are defined in YAML files stored in the .github/workflows directory.",
         "options": [("YAML (.yml or .yaml)", True), ("JSON (.json)", False), ("XML (.xml)", False), ("TOML (.toml)", False)]},
        {"cert_code": "GH-300", "difficulty": "Easy", "skill_area": "GitHub Actions",
         "text": "What keyword in a GitHub Actions workflow file specifies what events trigger the workflow?",
         "explanation": "The 'on' keyword defines events that trigger the workflow, such as push, pull_request, or schedule.",
         "options": [("on", True), ("triggers", False), ("events", False), ("when", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "GitHub Actions",
         "text": "What is a GitHub Actions 'runner'?",
         "explanation": "A runner is a server that executes workflow jobs. GitHub provides hosted runners or you can self-host.",
         "options": [("A server that executes workflow jobs", True), ("A reusable workflow component", False), ("An environment variable store", False), ("A code review bot", False)]},
        {"cert_code": "GH-300", "difficulty": "Hard", "skill_area": "GitHub Actions",
         "text": "What is the difference between a GitHub Actions 'job' and a 'step'?",
         "explanation": "A job runs on one runner and contains multiple steps. A step is an individual task (shell command or action) within a job.",
         "options": [("A job runs on one runner; a step is one task within that job", True), ("A step runs on one runner; a job is a collection of runners", False), ("Jobs and steps are interchangeable", False), ("Steps always run in parallel; jobs run sequentially", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "GitHub Actions",
         "text": "How do you pass secrets to a GitHub Actions workflow securely?",
         "explanation": "Secrets are stored in repository or environment settings and referenced using the secrets context: ${{ secrets.MY_SECRET }}.",
         "options": [("Via the secrets context: ${{ secrets.MY_SECRET }}", True), ("Directly in the YAML file as plain text", False), ("In the .env file committed to the repo", False), ("As command-line arguments to the runner", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "GitHub Actions",
         "text": "What does the 'needs' keyword do in a GitHub Actions workflow?",
         "explanation": "The 'needs' keyword creates job dependencies — the dependent job only runs after all listed jobs complete successfully.",
         "options": [("Creates job dependencies so a job only runs after specified jobs succeed", True), ("Lists required secrets for a workflow", False), ("Specifies the runner OS needed", False), ("Declares required repository permissions", False)]},
        {"cert_code": "GH-300", "difficulty": "Hard", "skill_area": "GitHub Actions",
         "text": "What is a 'reusable workflow' in GitHub Actions?",
         "explanation": "A reusable workflow is a workflow file that can be called from other workflow files, reducing duplication across repositories.",
         "options": [("A workflow that can be called from other workflows to reduce duplication", True), ("A workflow that runs on a schedule", False), ("A workflow stored in the GitHub Actions Marketplace", False), ("A workflow that automatically retries on failure", False)]},
        {"cert_code": "GH-300", "difficulty": "Easy", "skill_area": "Repository Management",
         "text": "What is a Git branch protection rule primarily used for?",
         "explanation": "Branch protection rules enforce required reviews and status checks before changes can be merged into protected branches.",
         "options": [("Enforce required reviews and status checks before merging", True), ("Prevent all commits to a branch", False), ("Automatically merge pull requests", False), ("Encrypt branch contents", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "Repository Management",
         "text": "What is a CODEOWNERS file used for in GitHub?",
         "explanation": "CODEOWNERS defines individuals or teams responsible for code; they are auto-requested as reviewers on PRs touching their code.",
         "options": [("Define required reviewers for PRs affecting specific files", True), ("List all repository collaborators", False), ("Define CI/CD pipeline owners", False), ("Set file permissions in the repository", False)]},
        {"cert_code": "GH-300", "difficulty": "Hard", "skill_area": "Repository Management",
         "text": "What is the difference between a fork and a branch in GitHub?",
         "explanation": "A fork is a full copy of a repository in a different account; a branch is a parallel line of development within the same repository.",
         "options": [("A fork is a copy in a different account; a branch is in the same repo", True), ("They are identical concepts with different names", False), ("A branch is a copy of the entire repo; a fork is a lightweight pointer", False), ("Forks are only for public repositories", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "Security & Compliance",
         "text": "What does GitHub Dependabot do?",
         "explanation": "Dependabot automatically opens pull requests to update dependencies when security vulnerabilities or newer versions are detected.",
         "options": [("Automatically creates PRs to update vulnerable or outdated dependencies", True), ("Scans code for hardcoded secrets", False), ("Runs security penetration tests", False), ("Manages team access permissions", False)]},
        {"cert_code": "GH-300", "difficulty": "Hard", "skill_area": "Security & Compliance",
         "text": "What is GitHub Advanced Security's Secret Scanning feature?",
         "explanation": "Secret Scanning automatically detects tokens, keys, and credentials accidentally committed to a repository.",
         "options": [("Detects accidentally committed secrets and credentials in repositories", True), ("Scans for SQL injection vulnerabilities", False), ("Monitors API rate limits", False), ("Encrypts sensitive files at rest", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "Security & Compliance",
         "text": "What is CodeQL in GitHub Advanced Security?",
         "explanation": "CodeQL is a static analysis engine that treats code as data, allowing queries to find security vulnerabilities and bugs automatically.",
         "options": [("A static analysis engine that finds security vulnerabilities in code", True), ("A code quality linter for style enforcement", False), ("A dependency scanner for open-source licenses", False), ("A runtime monitoring tool for deployed apps", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "GitHub Packages & Codespaces",
         "text": "What is GitHub Packages?",
         "explanation": "GitHub Packages is a package registry for npm, Maven, NuGet, Docker, and other types, integrated with GitHub.",
         "options": [("A package registry integrated with GitHub for hosting software packages", True), ("A marketplace for GitHub Apps only", False), ("A code archiving service", False), ("A binary deployment service for cloud VMs", False)]},
        {"cert_code": "GH-300", "difficulty": "Easy", "skill_area": "GitHub Packages & Codespaces",
         "text": "What is GitHub Codespaces?",
         "explanation": "GitHub Codespaces provides cloud-hosted development environments configured by devcontainer.json, accessible from browser or VS Code.",
         "options": [("A cloud-hosted development environment accessible from browser or VS Code", True), ("A local IDE plugin for GitHub", False), ("A GitHub Actions runner type", False), ("A code review collaboration tool", False)]},
        {"cert_code": "GH-300", "difficulty": "Hard", "skill_area": "GitHub Enterprise",
         "text": "What is GitHub Enterprise Managed Users (EMU)?",
         "explanation": "EMU allows enterprises to provision and manage GitHub user accounts via their IdP (e.g., Entra ID), giving full control over identities.",
         "options": [("Enterprise-controlled user accounts provisioned via an identity provider", True), ("A self-hosted version of GitHub", False), ("Multi-factor authentication enforcement", False), ("Shared service accounts for automation", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "GitHub Enterprise",
         "text": "What is the purpose of GitHub Environment protection rules?",
         "explanation": "Environment protection rules gate deployments — requiring approvals, restricting branches, or enforcing wait timers.",
         "options": [("Gate deployments with approvals and branch restrictions", True), ("Prevent public access to repositories", False), ("Enforce commit signing requirements", False), ("Control who can create new environments", False)]},
        {"cert_code": "GH-300", "difficulty": "Hard", "skill_area": "GitHub Enterprise",
         "text": "What is GitHub Connect used for in GitHub Enterprise Server?",
         "explanation": "GitHub Connect allows GitHub Enterprise Server to share features and data with GitHub.com, such as unified search and license usage.",
         "options": [("Share features between GitHub Enterprise Server and GitHub.com", True), ("Connect GitHub to Azure DevOps pipelines", False), ("Enable SSO for enterprise organizations", False), ("Sync repositories between two enterprise servers", False)]},
        {"cert_code": "GH-300", "difficulty": "Medium", "skill_area": "Repository Management",
         "text": "What is a GitHub Pull Request template used for?",
         "explanation": "PR templates pre-populate pull request descriptions with a consistent structure, prompting authors to include relevant context and checklists.",
         "options": [("Pre-populate PR descriptions with a consistent structure and checklist", True), ("Automatically approve PRs meeting certain criteria", False), ("Define which files are included in a PR", False), ("Set the merge strategy for a repository", False)]},
        {"cert_code": "GH-300", "difficulty": "Easy", "skill_area": "GitHub Actions",
         "text": "What is a GitHub Actions 'composite action'?",
         "explanation": "A composite action combines multiple workflow steps into a single reusable action, reducing duplication within and across workflows.",
         "options": [("A reusable action that combines multiple workflow steps", True), ("An action that runs on multiple operating systems simultaneously", False), ("A workflow triggered by composite events", False), ("An action that calls external APIs", False)]},

        # ── AI-103 (20 questions) ─────────────────────────────────────────────
        {"cert_code": "AI-103", "difficulty": "Easy", "skill_area": "LLM Fundamentals",
         "text": "What does 'LLM' stand for in the context of AI?",
         "explanation": "LLM stands for Large Language Model — a deep learning model trained on vast text data to understand and generate language.",
         "options": [("Large Language Model", True), ("Logical Learning Module", False), ("Linear Layer Matrix", False), ("Low-Level Machine", False)]},
        {"cert_code": "AI-103", "difficulty": "Easy", "skill_area": "LLM Fundamentals",
         "text": "What is 'tokenization' in the context of LLMs?",
         "explanation": "Tokenization splits text into smaller units (tokens) that the model processes. Tokens can be words, subwords, or characters.",
         "options": [("Splitting text into smaller units for model processing", True), ("Encrypting API keys for secure access", False), ("Counting the cost of API calls", False), ("Converting images to text", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "LLM Fundamentals",
         "text": "What is 'hallucination' in LLMs?",
         "explanation": "Hallucination is when an LLM generates information that sounds plausible but is factually incorrect or entirely fabricated.",
         "options": [("When an LLM generates plausible but factually incorrect information", True), ("When an LLM refuses to answer a question", False), ("When an LLM produces duplicate responses", False), ("When an LLM runs out of context window space", False)]},
        {"cert_code": "AI-103", "difficulty": "Hard", "skill_area": "LLM Fundamentals",
         "text": "What is the 'context window' of an LLM?",
         "explanation": "The context window is the maximum number of tokens a model can process in a single inference call, including input and output.",
         "options": [("Maximum tokens a model can process in a single call (input + output)", True), ("The training dataset size", False), ("The number of parameters in the model", False), ("The GPU memory available for inference", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "LLM Fundamentals",
         "text": "What is 'temperature' in LLM inference?",
         "explanation": "Temperature controls the randomness of model outputs. Higher = more creative; lower = more deterministic.",
         "options": [("A parameter controlling the randomness of model outputs", True), ("The GPU heat threshold during inference", False), ("The model's confidence score threshold", False), ("The maximum response length limit", False)]},
        {"cert_code": "AI-103", "difficulty": "Easy", "skill_area": "Prompt Engineering",
         "text": "What is 'zero-shot prompting'?",
         "explanation": "Zero-shot prompting asks the model to perform a task without providing any examples.",
         "options": [("Asking the model to perform a task without any examples", True), ("Providing many labeled examples in the prompt", False), ("Fine-tuning the model on task-specific data", False), ("Prompting with chain-of-thought reasoning", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "Prompt Engineering",
         "text": "What is 'few-shot prompting'?",
         "explanation": "Few-shot prompting includes a small number of examples in the prompt to guide the model's response format and style.",
         "options": [("Providing a few examples in the prompt to guide model behavior", True), ("Limiting the model to a few tokens in its response", False), ("Using a smaller, cheaper model", False), ("Batching multiple prompts into one API call", False)]},
        {"cert_code": "AI-103", "difficulty": "Hard", "skill_area": "Prompt Engineering",
         "text": "What is 'Chain-of-Thought (CoT) prompting'?",
         "explanation": "CoT prompting encourages the model to show intermediate reasoning steps, significantly improving accuracy on complex tasks.",
         "options": [("Guiding the model to reason step-by-step before answering", True), ("Chaining multiple API calls in sequence", False), ("Using a system prompt with a chain of rules", False), ("Connecting multiple LLMs in a pipeline", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "Prompt Engineering",
         "text": "What is 'prompt injection'?",
         "explanation": "Prompt injection is a security attack where malicious input overrides system instructions, causing unexpected behavior.",
         "options": [("A security attack where malicious input overrides system instructions", True), ("Adding context to a prompt dynamically", False), ("Injecting examples into a few-shot prompt", False), ("Streaming model responses incrementally", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "Prompt Engineering",
         "text": "What is 'system prompt' in LLM interactions?",
         "explanation": "A system prompt is an initial instruction given to the model before the user conversation begins, shaping its persona and behavior.",
         "options": [("Initial instructions that shape the model's behavior before user conversation", True), ("The first message sent by the user", False), ("A hidden watermark in model outputs", False), ("Instructions for tokenizing input text", False)]},
        {"cert_code": "AI-103", "difficulty": "Easy", "skill_area": "RAG & Vector Databases",
         "text": "What does 'RAG' stand for in AI engineering?",
         "explanation": "RAG stands for Retrieval-Augmented Generation — a technique that retrieves relevant documents and provides them as context to the LLM.",
         "options": [("Retrieval-Augmented Generation", True), ("Random Attention Gating", False), ("Recursive Autoencoder Graph", False), ("Relational AI Gateway", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "RAG & Vector Databases",
         "text": "What is the role of a vector database in a RAG system?",
         "explanation": "A vector database stores text embeddings and enables fast semantic similarity search to retrieve relevant documents.",
         "options": [("Stores embeddings and performs semantic similarity search", True), ("Stores raw documents as plain text", False), ("Runs the LLM inference", False), ("Manages API rate limits", False)]},
        {"cert_code": "AI-103", "difficulty": "Hard", "skill_area": "RAG & Vector Databases",
         "text": "What is 'chunking' in the context of building a RAG pipeline?",
         "explanation": "Chunking splits source documents into smaller segments before embedding, balancing context richness with retrieval precision.",
         "options": [("Splitting documents into smaller segments for embedding and retrieval", True), ("Compressing model weights for faster inference", False), ("Batching API requests to reduce latency", False), ("Dividing training data for fine-tuning", False)]},
        {"cert_code": "AI-103", "difficulty": "Hard", "skill_area": "RAG & Vector Databases",
         "text": "What is 'semantic search' and how does it differ from keyword search?",
         "explanation": "Semantic search uses vector embeddings to find results by meaning; keyword search matches exact terms — semantic handles synonyms better.",
         "options": [("Searches by meaning using embeddings; keyword search matches exact terms", True), ("Semantic search is always faster than keyword search", False), ("Keyword search is more accurate for technical documents", False), ("They use the same mechanism with different interfaces", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "MLOps & Deployment",
         "text": "What is model 'fine-tuning' in AI engineering?",
         "explanation": "Fine-tuning adapts a pre-trained model to a specific task or domain by continuing training on a smaller, task-specific dataset.",
         "options": [("Continuing training a pre-trained model on task-specific data", True), ("Adjusting hyperparameters after deployment", False), ("Compressing the model for edge deployment", False), ("Updating prompt templates in production", False)]},
        {"cert_code": "AI-103", "difficulty": "Hard", "skill_area": "MLOps & Deployment",
         "text": "What is 'model drift' and why does it matter in production AI systems?",
         "explanation": "Model drift is performance degradation over time due to changes in data distribution (data drift) or real-world patterns (concept drift).",
         "options": [("Performance degradation due to changing data or real-world patterns", True), ("Model parameters changing during inference", False), ("GPU memory fragmentation over time", False), ("API version deprecation", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "MLOps & Deployment",
         "text": "What is A/B testing in the context of LLM deployment?",
         "explanation": "A/B testing routes a portion of traffic to a new model version and compares metrics against the existing version before full rollout.",
         "options": [("Routing traffic between model versions to compare performance", True), ("Testing prompts with two different users", False), ("Running the model on two different cloud providers", False), ("Comparing training and validation loss curves", False)]},
        {"cert_code": "AI-103", "difficulty": "Medium", "skill_area": "MLOps & Deployment",
         "text": "What is a 'model card'?",
         "explanation": "A model card documents a model's intended use, performance metrics, training data, limitations, and ethical considerations.",
         "options": [("Documentation describing a model's intended use, performance, and limitations", True), ("An API key card for accessing model endpoints", False), ("A benchmark comparison between two models", False), ("A UI component for displaying model outputs", False)]},
        {"cert_code": "AI-103", "difficulty": "Easy", "skill_area": "AI Safety & Ethics",
         "text": "What is 'AI alignment' concerned with?",
         "explanation": "AI alignment is the challenge of ensuring AI systems pursue goals consistent with human values and intentions.",
         "options": [("Ensuring AI systems behave in accordance with human values and intentions", True), ("Aligning model weights symmetrically during training", False), ("Matching AI output format to UI requirements", False), ("Synchronizing model versions across deployments", False)]},
        {"cert_code": "AI-103", "difficulty": "Hard", "skill_area": "AI Safety & Ethics",
         "text": "What is 'RLHF' and why is it used in training modern LLMs?",
         "explanation": "RLHF (Reinforcement Learning from Human Feedback) fine-tunes models using human preference data to make them more helpful, harmless, and honest.",
         "options": [("Training with human preference feedback to make models more helpful and safe", True), ("A technique to reduce hallucinations via rule-based filters", False), ("Automated testing framework for LLM outputs", False), ("A retrieval method for knowledge base augmentation", False)]},
    ]

    cert_objects = {}
    for c in certs:
        cert = Certification(id=str(uuid.uuid4()), **c)
        db.add(cert)
        cert_objects[c["code"]] = cert

    db.flush()

    for code, skills in skills_map.items():
        cert = cert_objects[code]
        for i, skill in enumerate(skills):
            db.add(CertificationSkill(id=str(uuid.uuid4()), certification_id=cert.id, skill_name=skill, display_order=i))

    for q in questions_seed:
        cert = cert_objects[q["cert_code"]]
        question = Question(
            id=str(uuid.uuid4()),
            certification_id=cert.id,
            question_text=q["text"],
            explanation=q["explanation"],
            difficulty=q["difficulty"],
            skill_area=q["skill_area"],
            question_type="single",
        )
        db.add(question)
        db.flush()
        for i, (opt_text, is_correct) in enumerate(q["options"]):
            db.add(QuestionOption(
                id=str(uuid.uuid4()),
                question_id=question.id,
                option_text=opt_text,
                is_correct=is_correct,
                display_order=i,
            ))

    db.commit()
