import { Question, ExamSession, ExamMode, EXAM_BLUEPRINTS, QuestionType, Difficulty } from "@/types/exam";

const MOCK_QUESTIONS: Question[] = [
  {
    questionId: "q-ai102-001",
    exam: "AI-102",
    objective: "Implement Natural Language Processing Solutions",
    difficulty: "Medium",
    type: "MultipleChoiceSingle",
    question: "You are developing an Azure AI Language solution that needs to extract key phrases and detect the sentiment of customer feedback. The solution must process **10,000 requests per minute** at peak load. Which Azure AI Language feature combination should you use?",
    options: [
      { id: "A", text: "Custom text classification with a training dataset of 200 labeled samples" },
      { id: "B", text: "Key phrase extraction and sentiment analysis using the pre-built models with batch processing" },
      { id: "C", text: "Named entity recognition (NER) with a custom entity model trained on domain-specific data" },
      { id: "D", text: "Conversational language understanding (CLU) with intent classification" },
    ],
    correctAnswer: ["B"],
    explanation: "Azure AI Language provides pre-built models for key phrase extraction and sentiment analysis that require no training data. Using batch processing endpoints allows high-throughput workloads. Custom models (A, C) require training data and are suited for domain-specific tasks, not general sentiment/key phrase extraction. CLU (D) is designed for conversational AI, not bulk text analysis.",
    whyCorrect: "Pre-built key phrase extraction and sentiment analysis models are production-ready, require no training, and support batch endpoints that can handle 10,000+ requests/minute. Batch processing reduces latency and cost at scale.",
    whyIncorrect: {
      A: "Custom text classification requires labeled training data and is designed for categorizing documents into custom categories — not for key phrase extraction or sentiment analysis.",
      C: "NER with a custom model is appropriate for extracting domain-specific entities (e.g., medical terms), not for general sentiment or key phrase tasks.",
      D: "CLU is designed for building conversational AI applications that understand user intents and entities in chat or voice interfaces, not for batch text analytics.",
    },
    references: [
      { title: "Azure AI Language - Key Phrase Extraction", url: "https://learn.microsoft.com/azure/ai-services/language-service/key-phrase-extraction/overview" },
      { title: "Azure AI Language - Sentiment Analysis", url: "https://learn.microsoft.com/azure/ai-services/language-service/sentiment-opinion-mining/overview" },
      { title: "Batch Processing in Azure AI Language", url: "https://learn.microsoft.com/azure/ai-services/language-service/concepts/use-asynchronously" },
    ],
    grounding: { groundingScore: 0.94, citationCoverage: 0.91, retrievedDocumentIds: ["doc-lang-001", "doc-lang-002", "doc-batch-001"] },
    tags: ["NLP", "Language Service", "Batch Processing"],
  },
  {
    questionId: "q-ai102-002",
    exam: "AI-102",
    objective: "Implement Generative AI Solutions",
    difficulty: "Hard",
    type: "MultipleChoiceMultiple",
    question: "A financial services company wants to build a RAG-based document Q&A system using Azure OpenAI and Azure AI Search. The system must:\n\n- Prevent the model from answering questions not grounded in company documents\n- Reduce hallucination risk\n- Support documents in PDF and Word format\n\nWhich **three** actions should you take? (Select all that apply)",
    options: [
      { id: "A", text: "Configure Azure AI Search with semantic ranking and set `query_type` to `semantic`" },
      { id: "B", text: "Use the `max_tokens` parameter to limit response length to reduce hallucinations" },
      { id: "C", text: "Use Azure Document Intelligence to extract text from PDFs and Word documents before indexing" },
      { id: "D", text: "Add a system prompt instructing the model to only answer based on provided context and respond 'I don't know' if the answer is not in the documents" },
      { id: "E", text: "Enable Azure OpenAI content filtering to block financial advice" },
    ],
    correctAnswer: ["A", "C", "D"],
    explanation: "Building a reliable RAG system requires: (A) semantic search for better chunk relevance, (C) document intelligence to handle PDF/Word format extraction, and (D) a grounding system prompt to prevent out-of-context answers. max_tokens (B) limits length but doesn't prevent hallucination. Content filtering (E) is for safety, not grounding.",
    whyCorrect: "Semantic ranking improves retrieval precision by understanding query intent. Azure Document Intelligence handles complex document formats including tables and forms. A grounding system prompt is the primary technique for preventing the model from answering beyond retrieved context.",
    whyIncorrect: {
      B: "max_tokens controls response length but does not prevent the model from hallucinating — it simply truncates responses. It has no grounding effect.",
      E: "Content filtering prevents harmful content (violence, hate speech, etc.) but does not restrict the model to document-grounded answers.",
    },
    references: [
      { title: "Azure OpenAI On Your Data", url: "https://learn.microsoft.com/azure/ai-services/openai/concepts/use-your-data" },
      { title: "Azure AI Search - Semantic Ranking", url: "https://learn.microsoft.com/azure/search/semantic-how-to-query-request" },
      { title: "Azure Document Intelligence", url: "https://learn.microsoft.com/azure/ai-services/document-intelligence/overview" },
    ],
    grounding: { groundingScore: 0.96, citationCoverage: 0.93, retrievedDocumentIds: ["doc-openai-001", "doc-search-001", "doc-di-001"] },
    tags: ["RAG", "Azure OpenAI", "Azure AI Search", "Grounding"],
  },
  {
    questionId: "q-ai102-003",
    exam: "AI-102",
    objective: "Implement Computer Vision Solutions",
    difficulty: "Easy",
    type: "YesNo",
    question: "Azure AI Vision Image Analysis 4.0 can generate natural language captions for images without requiring any model training.",
    correctAnswer: ["Yes"],
    explanation: "Azure AI Vision Image Analysis 4.0 includes a pre-built image captioning feature powered by Florence foundation models that generates natural language descriptions of images. No custom training is required — it works out-of-the-box with the `/analyze` endpoint using the `caption` visual feature.",
    whyCorrect: "Image Analysis 4.0 uses Microsoft's Florence foundation model which has been pre-trained on billions of image-text pairs. The captioning capability is available via the REST API or SDK without any training or fine-tuning.",
    whyIncorrect: {
      No: "This would be incorrect because caption generation is a pre-built feature of Image Analysis 4.0 that requires no training data or model customization.",
    },
    references: [
      { title: "Azure AI Vision Image Analysis 4.0 Overview", url: "https://learn.microsoft.com/azure/ai-services/computer-vision/overview-image-analysis" },
      { title: "Image Captioning in Azure AI Vision", url: "https://learn.microsoft.com/azure/ai-services/computer-vision/concept-describe-images-40" },
    ],
    grounding: { groundingScore: 0.97, citationCoverage: 0.95, retrievedDocumentIds: ["doc-vision-001"] },
    tags: ["Computer Vision", "Image Analysis", "Florence"],
  },
  {
    questionId: "q-ai102-004",
    exam: "AI-102",
    objective: "Implement Knowledge Mining and Document Intelligence Solutions",
    difficulty: "Hard",
    type: "BuildList",
    question: "You are building an Azure AI Search knowledge mining pipeline that indexes PDF documents from Azure Blob Storage and enables semantic search. Arrange the steps in the correct order to set up this pipeline:",
    buildItems: [
      "Create an Azure AI Search service and define an index schema",
      "Create a data source connection pointing to the Azure Blob Storage container",
      "Create a skillset with OCR and text extraction skills",
      "Create an indexer that connects the data source, skillset, and index",
      "Enable semantic configuration on the index",
      "Run the indexer and verify document ingestion",
    ],
    correctAnswer: [
      "Create an Azure AI Search service and define an index schema",
      "Create a data source connection pointing to the Azure Blob Storage container",
      "Create a skillset with OCR and text extraction skills",
      "Create an indexer that connects the data source, skillset, and index",
      "Enable semantic configuration on the index",
      "Run the indexer and verify document ingestion",
    ],
    explanation: "The correct Azure AI Search pipeline creation order follows a dependency chain: the index schema must exist before the indexer can map fields to it; the data source must be created before the indexer references it; the skillset must exist before the indexer applies it; semantic configuration is applied after index creation; finally the indexer is run to trigger ingestion.",
    whyCorrect: "This order respects Azure AI Search's dependency model: index → data source + skillset → indexer → semantic config → run. Each component references the previously created components.",
    whyIncorrect: {},
    references: [
      { title: "Azure AI Search Indexer Overview", url: "https://learn.microsoft.com/azure/search/search-indexer-overview" },
      { title: "Azure AI Search Skillsets", url: "https://learn.microsoft.com/azure/search/cognitive-search-concept-intro" },
      { title: "Semantic Search in Azure AI Search", url: "https://learn.microsoft.com/azure/search/semantic-how-to-configure" },
    ],
    grounding: { groundingScore: 0.93, citationCoverage: 0.89, retrievedDocumentIds: ["doc-search-002", "doc-search-003"] },
    tags: ["Azure AI Search", "Knowledge Mining", "Indexer"],
  },
  {
    questionId: "q-ai102-005",
    exam: "AI-102",
    objective: "Plan and Manage an Azure AI Solution",
    difficulty: "Medium",
    type: "MatchFollowing",
    question: "Match each Azure AI service to its primary use case:",
    matchPairs: [
      { left: "Azure AI Language", right: "Extract meaning from text, detect sentiment, identify named entities" },
      { left: "Azure AI Speech", right: "Convert spoken audio to text and text to natural-sounding speech" },
      { left: "Azure AI Vision", right: "Analyze images, detect objects, extract text from images" },
      { left: "Azure OpenAI Service", right: "Access GPT-4, DALL-E, and Whisper models via REST API" },
    ],
    correctAnswer: [
      "Azure AI Language=Extract meaning from text, detect sentiment, identify named entities",
      "Azure AI Speech=Convert spoken audio to text and text to natural-sounding speech",
      "Azure AI Vision=Analyze images, detect objects, extract text from images",
      "Azure OpenAI Service=Access GPT-4, DALL-E, and Whisper models via REST API",
    ],
    explanation: "Each Azure AI service addresses a specific modality: Language for text understanding, Speech for audio, Vision for images, and OpenAI Service for large language models and generative AI.",
    whyCorrect: "These are the canonical service definitions from Microsoft documentation. Each service is purpose-built for its modality.",
    whyIncorrect: {},
    references: [
      { title: "Azure AI Services Overview", url: "https://learn.microsoft.com/azure/ai-services/what-are-ai-services" },
    ],
    grounding: { groundingScore: 0.98, citationCoverage: 0.97, retrievedDocumentIds: ["doc-ai-overview-001"] },
    tags: ["Azure AI Services", "Service Overview"],
  },
  {
    questionId: "q-ai102-006",
    exam: "AI-102",
    objective: "Implement Generative AI Solutions",
    difficulty: "Hard",
    type: "ScenarioArchitecture",
    question: "A healthcare company is deploying an Azure OpenAI-powered chatbot for clinical staff. The system must:\n\n- Ensure responses are only based on approved clinical documentation\n- Filter responses that contain personally identifiable information (PII)\n- Log all interactions for compliance\n- Operate with sub-2-second response latency\n\nWhich architecture best satisfies ALL requirements?",
    context: "The company has 50,000 approved clinical documents stored in Azure Blob Storage. The chatbot will serve 500 concurrent users during peak hours.",
    options: [
      {
        id: "A",
        text: "Azure OpenAI with system prompt → Azure API Management (rate limiting) → Azure Monitor logging",
      },
      {
        id: "B",
        text: "Azure AI Search (vector index of docs) → Azure OpenAI with grounding system prompt → Azure AI Language PII detection → Azure Cosmos DB (audit log) → Redis Cache (response caching)",
      },
      {
        id: "C",
        text: "Azure OpenAI fine-tuned on clinical documents → Azure Functions (orchestration) → Azure SQL (logging)",
      },
      {
        id: "D",
        text: "Azure Cognitive Search (keyword search) → Azure OpenAI → Azure Blob Storage (log storage)",
      },
    ],
    correctAnswer: ["B"],
    explanation: "Option B satisfies all requirements: Azure AI Search with vector indexing provides document-grounded responses (RAG), the grounding system prompt prevents out-of-context answers, Azure AI Language PII detection filters PII from responses, Cosmos DB provides audit logging with sub-millisecond writes, and Redis Cache reduces repeated query latency below 2 seconds.",
    whyCorrect: "Option B is the only architecture that addresses all four requirements simultaneously: grounding (AI Search + system prompt), PII filtering (AI Language), compliance logging (Cosmos DB), and low latency (Redis caching).",
    whyIncorrect: {
      A: "Missing: document grounding (only system prompt, no retrieval), PII filtering, and low latency caching. Relies entirely on model memory for clinical knowledge.",
      C: "Fine-tuning embeds knowledge in model weights but doesn't prevent hallucination and is extremely expensive to update when documents change. Also lacks PII filtering.",
      D: "Keyword search has lower recall than vector search for clinical queries. No PII filtering, no caching, and Azure Blob Storage is not suitable for structured audit logging.",
    },
    references: [
      { title: "Azure OpenAI RAG Pattern", url: "https://learn.microsoft.com/azure/ai-services/openai/use-your-data-quickstart" },
      { title: "PII Detection in Azure AI Language", url: "https://learn.microsoft.com/azure/ai-services/language-service/personally-identifiable-information/overview" },
      { title: "Azure Architecture Center - Conversational Bot", url: "https://learn.microsoft.com/azure/architecture/ai-ml/idea/conversational-bot" },
    ],
    grounding: { groundingScore: 0.95, citationCoverage: 0.92, retrievedDocumentIds: ["doc-openai-002", "doc-lang-003", "doc-arch-001"] },
    tags: ["Architecture", "RAG", "Healthcare", "PII", "OpenAI"],
  },
  {
    questionId: "q-ai102-007",
    exam: "AI-102",
    objective: "Implement Natural Language Processing Solutions",
    difficulty: "Medium",
    type: "DragAndDrop",
    question: "Classify each Azure AI Language capability into the correct category:",
    dragItems: [
      "Sentiment analysis",
      "Custom NER",
      "Conversational Language Understanding",
      "Key phrase extraction",
      "Custom text classification",
      "Question answering",
    ],
    dropZones: ["Pre-built (No Training Required)", "Custom (Training Required)"],
    correctAnswer: [
      "Sentiment analysis->Pre-built (No Training Required)",
      "Key phrase extraction->Pre-built (No Training Required)",
      "Question answering->Pre-built (No Training Required)",
      "Custom NER->Custom (Training Required)",
      "Conversational Language Understanding->Custom (Training Required)",
      "Custom text classification->Custom (Training Required)",
    ],
    explanation: "Azure AI Language provides both pre-built models (ready to use without training) and custom models (requiring labeled training data). Pre-built: sentiment analysis, key phrase extraction, language detection, NER (general), question answering with pre-built KB. Custom: custom NER (your entity types), CLU (your intents/entities), custom text classification (your categories).",
    whyCorrect: "Pre-built models are trained by Microsoft on large, general datasets. Custom models use transfer learning from Microsoft's foundation models but require your domain-specific training data.",
    whyIncorrect: {},
    references: [
      { title: "Azure AI Language Service Overview", url: "https://learn.microsoft.com/azure/ai-services/language-service/overview" },
      { title: "Custom vs Pre-built Features", url: "https://learn.microsoft.com/azure/ai-services/language-service/concepts/custom-features" },
    ],
    grounding: { groundingScore: 0.96, citationCoverage: 0.94, retrievedDocumentIds: ["doc-lang-004"] },
    tags: ["NLP", "Language Service", "Custom Models"],
  },
  {
    questionId: "q-az104-001",
    exam: "AZ-104",
    objective: "Manage Azure Identities and Governance",
    difficulty: "Medium",
    type: "MultipleChoiceSingle",
    question: "Your organization has a policy that Azure resources must have a `CostCenter` tag with a valid value before they can be deployed. You need to enforce this policy across all subscriptions in your management group. What should you configure?",
    options: [
      { id: "A", text: "Azure Policy with the `Deny` effect targeting the management group, requiring the `CostCenter` tag on all resources" },
      { id: "B", text: "Azure RBAC with a custom role that denies `Microsoft.Resources/deployments/write` for resources without tags" },
      { id: "C", text: "Azure Blueprints with a policy assignment that audits tag compliance" },
      { id: "D", text: "Management group locks with a CanNotModify lock on all subscriptions" },
    ],
    correctAnswer: ["A"],
    explanation: "Azure Policy with the `Deny` effect at the management group scope is the correct tool for enforcing resource tagging compliance. It prevents non-compliant resource deployments before they occur. RBAC cannot evaluate tag values. Azure Blueprints wraps policies but using `Audit` effect doesn't block deployments. Management locks prevent deletion/modification of existing resources, not tag enforcement.",
    whyCorrect: "Azure Policy with `Deny` effect blocks resource creation/modification if the `CostCenter` tag is missing or has an invalid value. Applying it at the management group level ensures coverage across all child subscriptions.",
    whyIncorrect: {
      B: "Azure RBAC controls who can perform actions, not what configuration resources must have. RBAC cannot enforce tag requirements.",
      C: "Azure Blueprints with `Audit` effect only reports non-compliance, it doesn't prevent resource deployment. You would need `Deny` effect.",
      D: "Management locks (ReadOnly / CanNotDelete) prevent modification and deletion of existing resources, they don't govern tag requirements on new deployments.",
    },
    references: [
      { title: "Azure Policy - Require Tag with Value", url: "https://learn.microsoft.com/azure/governance/policy/samples/require-tag-value" },
      { title: "Azure Policy - Understand Effects", url: "https://learn.microsoft.com/azure/governance/policy/concepts/effects" },
      { title: "Organize Resources with Management Groups", url: "https://learn.microsoft.com/azure/governance/management-groups/overview" },
    ],
    grounding: { groundingScore: 0.95, citationCoverage: 0.93, retrievedDocumentIds: ["doc-policy-001", "doc-mg-001"] },
    tags: ["Azure Policy", "Governance", "Tags", "Management Groups"],
  },
  // AZ-305 questions
  {
    questionId: "q-az305-001",
    exam: "AZ-305",
    objective: "Design Infrastructure Solutions",
    difficulty: "Hard",
    type: "MultipleChoiceSingle",
    question: "A company needs to migrate a 3-tier web application to Azure. The application currently runs on 20 VMs and requires 99.99% uptime SLA. The database tier holds 10TB of relational data and cannot tolerate data loss. Which architecture best satisfies these requirements?",
    options: [
      { id: "A", text: "Azure Virtual Machines in a single availability set with Azure SQL Database Business Critical tier and geo-replication" },
      { id: "B", text: "Azure App Service (Standard tier) + Azure SQL Database (General Purpose) + Azure CDN" },
      { id: "C", text: "Azure Virtual Machine Scale Sets across Availability Zones + Azure SQL Hyperscale + Azure Site Recovery for DR" },
      { id: "D", text: "Azure Kubernetes Service + Azure SQL Managed Instance (Business Critical) + Zone-redundant configuration" },
    ],
    correctAnswer: ["D"],
    explanation: "AKS with zone-redundant deployment provides 99.99% SLA for the application tier. Azure SQL Managed Instance Business Critical tier with zone redundancy provides synchronous replication across zones with zero data loss (RPO=0). This is the only option that satisfies both the SLA and zero data loss requirements simultaneously.",
    whyCorrect: "AKS zone-redundant + SQL MI Business Critical is the only combination achieving 99.99% compute SLA with RPO=0 for a large relational database.",
    whyIncorrect: {
      A: "Single availability set only provides 99.95% SLA (2 fault domains), not 99.99%.",
      B: "App Service Standard tier only provides 99.95% SLA and doesn't handle 10TB workloads efficiently.",
      C: "Azure SQL Hyperscale with Site Recovery cannot guarantee zero data loss (Site Recovery has 15-min RPO).",
    },
    references: [{ title: "Azure SQL Managed Instance SLA", url: "https://learn.microsoft.com/azure/azure-sql/managed-instance/high-availability-sla-local-zone-redundancy" }],
    grounding: { groundingScore: 0.93, citationCoverage: 0.88, retrievedDocumentIds: ["doc-az305-001"] },
    tags: ["Architecture", "AKS", "SQL Managed Instance", "SLA"],
  },
  {
    questionId: "q-az305-002",
    exam: "AZ-305",
    objective: "Design Identity, Governance, and Monitoring Solutions",
    difficulty: "Medium",
    type: "MultipleChoiceMultiple",
    question: "A global enterprise needs to design an Azure governance solution. They have 5 business units, each needing isolated billing, separate resource policies, and the ability to share networking. Which **two** Azure constructs should you use to achieve this? (Select all that apply)",
    options: [
      { id: "A", text: "One management group per business unit with separate subscriptions per unit" },
      { id: "B", text: "A single subscription with resource groups per business unit" },
      { id: "C", text: "Azure Policy at management group scope to enforce compliance across all subscriptions" },
      { id: "D", text: "Azure Virtual WAN with hub-spoke topology for shared networking" },
    ],
    correctAnswer: ["A", "C"],
    explanation: "Separate subscriptions per business unit provide isolated billing and resource limits. Management groups enable policy and RBAC governance at scale above the subscription level. Azure Policy at management group scope enforces compliance across all child subscriptions without repeating assignments.",
    whyCorrect: "Separate subscriptions = isolated billing. Management groups + Azure Policy = centralized governance at scale.",
    whyIncorrect: {
      B: "Resource groups don't provide billing isolation — all resource groups within a subscription share the same billing account.",
      D: "Virtual WAN addresses network topology, not governance or billing isolation.",
    },
    references: [{ title: "Azure Management Groups", url: "https://learn.microsoft.com/azure/governance/management-groups/overview" }],
    grounding: { groundingScore: 0.91, citationCoverage: 0.86, retrievedDocumentIds: ["doc-az305-002"] },
    tags: ["Governance", "Management Groups", "Azure Policy"],
  },
  // GH-300 questions
  {
    questionId: "q-gh300-001",
    exam: "GH-300",
    objective: "Configure and Use Secret Scanning",
    difficulty: "Medium",
    type: "MultipleChoiceSingle",
    question: "A developer accidentally committed an AWS access key to a public GitHub repository. GitHub Advanced Security secret scanning detected the secret. What happens automatically after detection?",
    options: [
      { id: "A", text: "GitHub deletes the commit containing the secret" },
      { id: "B", text: "GitHub notifies the repository owner and the secret provider (AWS) via the partner program" },
      { id: "C", text: "GitHub creates a pull request to remove the secret from the repository" },
      { id: "D", text: "GitHub blocks all future pushes to the repository until the secret is rotated" },
    ],
    correctAnswer: ["B"],
    explanation: "GitHub's secret scanning partner program automatically notifies both the repository owner via a security alert and the affected service provider (AWS in this case). AWS can then immediately revoke or flag the exposed credential. GitHub does not automatically delete commits or block pushes.",
    whyCorrect: "The partner program allows GitHub to notify service providers in real-time, enabling immediate credential revocation before exploitation.",
    whyIncorrect: {
      A: "GitHub never automatically modifies git history — that would break repository integrity.",
      C: "GitHub doesn't automatically modify code or create PRs.",
      D: "Secret scanning doesn't block pushes; push protection is a separate feature.",
    },
    references: [{ title: "GitHub Secret Scanning Partner Program", url: "https://docs.github.com/en/code-security/secret-scanning/secret-scanning-patterns" }],
    grounding: { groundingScore: 0.95, citationCoverage: 0.91, retrievedDocumentIds: ["doc-gh300-001"] },
    tags: ["Secret Scanning", "GitHub Advanced Security", "Partner Program"],
  },
  {
    questionId: "q-gh300-002",
    exam: "GH-300",
    objective: "Configure and Use Dependabot",
    difficulty: "Easy",
    type: "YesNo",
    question: "Dependabot version updates can be configured to automatically create pull requests that update dependencies to their latest versions, even if no known vulnerability exists.",
    correctAnswer: ["Yes"],
    explanation: "Dependabot has two distinct features: (1) Dependabot alerts — notifies about known vulnerabilities in dependencies; (2) Dependabot version updates — proactively creates PRs to keep dependencies current, regardless of whether a CVE exists. Version updates are configured via `.github/dependabot.yml`.",
    whyCorrect: "Dependabot version updates is specifically designed for proactive dependency maintenance, creating PRs for any version update, not just security patches.",
    whyIncorrect: { No: "Dependabot version updates explicitly supports keeping dependencies current for non-security reasons." },
    references: [{ title: "Dependabot Version Updates", url: "https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates" }],
    grounding: { groundingScore: 0.97, citationCoverage: 0.95, retrievedDocumentIds: ["doc-gh300-002"] },
    tags: ["Dependabot", "Version Updates", "GitHub Advanced Security"],
  },
  // AB-100 questions
  {
    questionId: "q-ab100-001",
    exam: "AB-100",
    objective: "Describe Fundamental Principles of Machine Learning on Azure",
    difficulty: "Easy",
    type: "MultipleChoiceSingle",
    question: "A retail company wants to predict whether a customer will churn (leave) within the next 30 days based on purchase history. Which type of machine learning task is this?",
    options: [
      { id: "A", text: "Regression — predicting a continuous numerical value" },
      { id: "B", text: "Binary classification — predicting one of two possible outcomes" },
      { id: "C", text: "Clustering — grouping customers into similar segments" },
      { id: "D", text: "Anomaly detection — identifying unusual customer patterns" },
    ],
    correctAnswer: ["B"],
    explanation: "Predicting churn is a binary classification problem: the model predicts one of two outcomes — 'will churn' (Yes) or 'will not churn' (No). Regression predicts continuous values (e.g., predicted revenue). Clustering groups unlabeled data. Anomaly detection finds outliers.",
    whyCorrect: "Binary classification predicts between two discrete categories (churn/no-churn). The target variable is a boolean outcome, which is the defining characteristic of binary classification.",
    whyIncorrect: {
      A: "Regression predicts continuous values like prices or temperatures, not yes/no outcomes.",
      C: "Clustering is unsupervised — it groups data without predefined labels, not used for prediction.",
      D: "Anomaly detection identifies unusual patterns; churn prediction is a supervised classification task.",
    },
    references: [{ title: "Classification Machine Learning", url: "https://learn.microsoft.com/azure/machine-learning/concept-automated-ml" }],
    grounding: { groundingScore: 0.96, citationCoverage: 0.92, retrievedDocumentIds: ["doc-ab100-001"] },
    tags: ["Machine Learning", "Classification", "AI Fundamentals"],
  },
  {
    questionId: "q-ab100-002",
    exam: "AB-100",
    objective: "Describe AI Workloads and Considerations",
    difficulty: "Easy",
    type: "MatchFollowing",
    question: "Match each responsible AI principle to its correct description:",
    matchPairs: [
      { left: "Fairness", right: "AI systems should treat all people equitably and avoid biased outcomes" },
      { left: "Reliability & Safety", right: "AI systems should perform as intended and handle unexpected situations safely" },
      { left: "Privacy & Security", right: "AI systems should protect personal data and respect user privacy" },
      { left: "Transparency", right: "AI systems should be understandable, and their decisions explainable" },
    ],
    correctAnswer: [
      "Fairness=AI systems should treat all people equitably and avoid biased outcomes",
      "Reliability & Safety=AI systems should perform as intended and handle unexpected situations safely",
      "Privacy & Security=AI systems should protect personal data and respect user privacy",
      "Transparency=AI systems should be understandable, and their decisions explainable",
    ],
    explanation: "Microsoft's Responsible AI principles include six pillars: Fairness, Reliability & Safety, Privacy & Security, Inclusiveness, Transparency, and Accountability. Each addresses a distinct dimension of ethical AI development.",
    whyCorrect: "These are the canonical definitions from Microsoft's Responsible AI framework.",
    whyIncorrect: {},
    references: [{ title: "Microsoft Responsible AI Principles", url: "https://learn.microsoft.com/azure/machine-learning/concept-responsible-ai" }],
    grounding: { groundingScore: 0.98, citationCoverage: 0.96, retrievedDocumentIds: ["doc-ab100-002"] },
    tags: ["Responsible AI", "AI Fundamentals", "Ethics"],
  },
  // AI-103 questions
  {
    questionId: "q-ai103-001",
    exam: "AI-103",
    objective: "Implement Advanced RAG and Knowledge Solutions",
    difficulty: "Hard",
    type: "MultipleChoiceMultiple",
    question: "You are designing an enterprise RAG system for a legal firm with 500,000 documents. The system must achieve sub-2-second latency, support semantic search across case law, and maintain citation accuracy above 95%. Which **three** architectural decisions are most critical? (Select all that apply)",
    options: [
      { id: "A", text: "Use HNSW vector index with IVF quantization in Azure AI Search to balance recall and query speed" },
      { id: "B", text: "Implement a hybrid search strategy combining vector similarity with BM25 keyword scoring" },
      { id: "C", text: "Store all documents in a single Azure AI Search index without chunking" },
      { id: "D", text: "Implement a reranking layer using a cross-encoder model after initial vector retrieval" },
      { id: "E", text: "Use GPT-4o with a strict grounding system prompt and citation injection for answer generation" },
    ],
    correctAnswer: ["B", "D", "E"],
    explanation: "For 500K legal documents: (B) Hybrid search combines semantic understanding of BM25 keyword matching with vector similarity for maximum recall on legal terminology; (D) Cross-encoder reranking dramatically improves precision by deeply comparing query-document pairs after initial retrieval; (E) Strict grounding with citation injection ensures ≥95% citation accuracy. HNSW with IVF quantization (A) trades recall for speed and may miss relevant precedents. Unchunked documents (C) exceed context windows.",
    whyCorrect: "Hybrid search + cross-encoder reranking + grounded generation is the production-proven pattern for high-accuracy enterprise RAG.",
    whyIncorrect: {
      A: "IVF quantization reduces vector precision and can hurt recall in legal search where finding exact precedents matters.",
      C: "Legal documents are too large for direct indexing — chunking is essential for context window management.",
    },
    references: [{ title: "Azure AI Search Hybrid Retrieval", url: "https://learn.microsoft.com/azure/search/hybrid-search-overview" }],
    grounding: { groundingScore: 0.94, citationCoverage: 0.90, retrievedDocumentIds: ["doc-ai103-001"] },
    tags: ["RAG", "Enterprise AI", "Hybrid Search", "Reranking"],
  },
  {
    questionId: "q-ai103-002",
    exam: "AI-103",
    objective: "Govern and Operate AI Solutions at Scale",
    difficulty: "Hard",
    type: "ScenarioArchitecture",
    question: "A financial services firm is deploying 12 generative AI applications across 3 Azure subscriptions. They need centralized cost control, consistent safety policies, and the ability to route traffic between GPT-4o and GPT-4o-mini based on query complexity. Which architecture component addresses ALL three requirements?",
    context: "Current state: Each team deploys their own Azure OpenAI instances with no central governance. Monthly AI spend is unpredictable and content policies vary by team.",
    options: [
      { id: "A", text: "Azure API Management with OpenAI plugin + policy fragments for rate limiting and content filtering" },
      { id: "B", text: "AI Gateway pattern using Azure API Management + Azure OpenAI Service (multiple deployments) + Azure Monitor for cost tracking + custom routing logic in APIM policies" },
      { id: "C", text: "Single Azure OpenAI instance shared across all teams with subscription-level cost alerts" },
      { id: "D", text: "Azure Load Balancer distributing traffic across multiple Azure OpenAI endpoints" },
    ],
    correctAnswer: ["B"],
    explanation: "The AI Gateway pattern (B) addresses all three: APIM provides centralized cost tracking via Azure Monitor integration and token-usage metrics; APIM policies enforce consistent safety/content policies across all 12 apps; routing logic in APIM policies can evaluate prompt complexity and route to GPT-4o vs GPT-4o-mini accordingly. Single instance (C) creates a bottleneck and quota issues. Azure Load Balancer (D) doesn't understand AI semantics for intelligent routing.",
    whyCorrect: "The AI Gateway pattern is the enterprise-standard architecture for governing multiple generative AI applications at scale, providing observability, policy enforcement, and intelligent routing in a single control plane.",
    whyIncorrect: {
      A: "APIM with OpenAI plugin handles content filtering but lacks the intelligent routing between model tiers.",
      C: "Single instance creates quota bottleneck for 12 apps and doesn't enable per-team cost attribution.",
      D: "Azure Load Balancer is L4 (TCP/UDP) — it can't inspect prompt content for intelligent routing decisions.",
    },
    references: [{ title: "AI Gateway Pattern with APIM", url: "https://learn.microsoft.com/azure/api-management/azure-openai-enable-semantic-caching" }],
    grounding: { groundingScore: 0.92, citationCoverage: 0.87, retrievedDocumentIds: ["doc-ai103-002"] },
    tags: ["AI Gateway", "APIM", "MLOps", "Governance"],
  },
  // AB-100 additional questions
  {
    questionId: "q-ab100-003",
    exam: "AB-100",
    objective: "Describe Features of Computer Vision Workloads on Azure",
    difficulty: "Easy",
    type: "MultipleChoiceSingle",
    question: "A developer wants to build an application that can automatically read text printed on product labels and extract the content as digital text. Which Azure AI service is most appropriate?",
    options: [
      { id: "A", text: "Azure AI Vision — Optical Character Recognition (OCR)" },
      { id: "B", text: "Azure AI Language — Named Entity Recognition" },
      { id: "C", text: "Azure AI Speech — Speech to Text" },
      { id: "D", text: "Azure AI Translator — Document Translation" },
    ],
    correctAnswer: ["A"],
    explanation: "Azure AI Vision includes Optical Character Recognition (OCR) capability that extracts printed and handwritten text from images. It can read text from product labels, signs, forms, and documents. Azure AI Language handles text understanding (not extraction from images). Speech services handle audio. Translator handles language translation, not image OCR.",
    whyCorrect: "OCR is the specific computer vision feature designed to extract text from images — exactly what's needed for reading product label text.",
    whyIncorrect: {
      B: "NER identifies named entities in text — it works on already-extracted text, not images.",
      C: "Speech to Text converts spoken audio to text, not printed text in images.",
      D: "Document Translation translates text between languages; it doesn't extract text from images.",
    },
    references: [{ title: "Azure AI Vision OCR Overview", url: "https://learn.microsoft.com/azure/ai-services/computer-vision/overview-ocr" }],
    grounding: { groundingScore: 0.97, citationCoverage: 0.95, retrievedDocumentIds: ["doc-ab100-003"] },
    tags: ["Computer Vision", "OCR", "AI Fundamentals"],
  },
  {
    questionId: "q-ab100-004",
    exam: "AB-100",
    objective: "Describe Features of NLP Workloads on Azure",
    difficulty: "Easy",
    type: "YesNo",
    question: "Azure AI Language can analyze a customer review and determine whether the sentiment is positive, negative, or mixed — without requiring any custom model training.",
    correctAnswer: ["Yes"],
    explanation: "Azure AI Language provides pre-built sentiment analysis as a ready-to-use feature. It can classify text as positive, negative, neutral, or mixed sentiment at both document and sentence levels. No training data or model customization is required — it works immediately via the API.",
    whyCorrect: "Sentiment analysis is a pre-built NLP feature in Azure AI Language powered by Microsoft's trained models, requiring zero setup or training data.",
    whyIncorrect: { No: "Sentiment analysis is specifically listed as a pre-built capability in Azure AI Language that works without custom model training." },
    references: [{ title: "Sentiment Analysis in Azure AI Language", url: "https://learn.microsoft.com/azure/ai-services/language-service/sentiment-opinion-mining/overview" }],
    grounding: { groundingScore: 0.98, citationCoverage: 0.96, retrievedDocumentIds: ["doc-ab100-004"] },
    tags: ["NLP", "Sentiment Analysis", "AI Fundamentals"],
  },
  {
    questionId: "q-ab100-005",
    exam: "AB-100",
    objective: "Describe Features of Generative AI Workloads on Azure",
    difficulty: "Medium",
    type: "MultipleChoiceSingle",
    question: "A company wants to add an AI assistant to their website that can answer questions about their products using only information from their product documentation. Which Azure service and technique should they use?",
    options: [
      { id: "A", text: "Azure OpenAI Service with fine-tuning on product documentation" },
      { id: "B", text: "Azure OpenAI Service with Retrieval Augmented Generation (RAG) using Azure AI Search" },
      { id: "C", text: "Azure AI Language with custom question answering trained on documentation" },
      { id: "D", text: "Azure Machine Learning AutoML trained on product FAQ data" },
    ],
    correctAnswer: ["B"],
    explanation: "RAG (Retrieval Augmented Generation) is the recommended pattern for grounding AI responses in specific documents. Azure AI Search indexes the product documentation, and Azure OpenAI Service retrieves relevant chunks to answer questions. This ensures responses are based on actual documentation without fine-tuning (which is expensive and requires retraining when docs change).",
    whyCorrect: "RAG with Azure AI Search + Azure OpenAI is the standard pattern for document-grounded Q&A — it's dynamic, doesn't require retraining when docs change, and prevents hallucination.",
    whyIncorrect: {
      A: "Fine-tuning embeds knowledge in model weights — it's expensive, requires large datasets, and must be redone every time documentation changes.",
      C: "Custom question answering is a simpler FAQ system; it doesn't handle complex generative responses or large documentation sets as effectively as RAG.",
      D: "AutoML is for structured prediction tasks, not for building conversational AI on documents.",
    },
    references: [{ title: "Azure OpenAI RAG Pattern", url: "https://learn.microsoft.com/azure/ai-services/openai/use-your-data-quickstart" }],
    grounding: { groundingScore: 0.95, citationCoverage: 0.92, retrievedDocumentIds: ["doc-ab100-005"] },
    tags: ["Generative AI", "RAG", "Azure OpenAI", "AI Fundamentals"],
  },
  {
    questionId: "q-ab100-006",
    exam: "AB-100",
    objective: "Describe Fundamental Principles of Machine Learning on Azure",
    difficulty: "Medium",
    type: "MultipleChoiceMultiple",
    question: "Which **two** statements about deep learning are correct? (Select all that apply)",
    options: [
      { id: "A", text: "Deep learning models use multiple layers of neurons to learn hierarchical feature representations" },
      { id: "B", text: "Deep learning always requires less training data than traditional machine learning algorithms" },
      { id: "C", text: "Deep learning is particularly effective for unstructured data like images, audio, and text" },
      { id: "D", text: "Deep learning models are always more interpretable than traditional ML models" },
    ],
    correctAnswer: ["A", "C"],
    explanation: "Deep learning uses neural networks with multiple hidden layers (A) — each layer learns increasingly abstract features (e.g., edges → shapes → objects in image recognition). Deep learning excels at unstructured data (C) like images, speech, and text where traditional ML struggles with feature engineering. Deep learning typically requires MORE data than traditional ML (not less), and deep learning models are generally LESS interpretable (black-box) than traditional models.",
    whyCorrect: "Multi-layer neural networks and effectiveness on unstructured data are the two defining characteristics of deep learning.",
    whyIncorrect: {
      B: "Deep learning typically requires significantly more training data than classical ML algorithms — this is a known limitation.",
      D: "Deep learning models are notoriously difficult to interpret — this is why explainable AI (XAI) is an active research area.",
    },
    references: [{ title: "Deep Learning Concepts", url: "https://learn.microsoft.com/azure/machine-learning/concept-deep-learning-vs-machine-learning" }],
    grounding: { groundingScore: 0.96, citationCoverage: 0.93, retrievedDocumentIds: ["doc-ab100-006"] },
    tags: ["Deep Learning", "Machine Learning", "AI Fundamentals"],
  },
  // AZ-104 additional questions
  {
    questionId: "q-az104-002",
    exam: "AZ-104",
    objective: "Implement and Manage Virtual Networking",
    difficulty: "Medium",
    type: "MultipleChoiceSingle",
    question: "You have two virtual networks in different Azure regions. VMs in VNet-A need to communicate with VMs in VNet-B using private IP addresses. What should you configure?",
    options: [
      { id: "A", text: "VPN Gateway with site-to-site connection between the two virtual networks" },
      { id: "B", text: "Global virtual network peering between VNet-A and VNet-B" },
      { id: "C", text: "Azure ExpressRoute circuit connecting the two virtual networks" },
      { id: "D", text: "Network Security Group rules allowing traffic between the two address spaces" },
    ],
    correctAnswer: ["B"],
    explanation: "Global VNet peering enables communication between virtual networks in different Azure regions using Microsoft's backbone network. Traffic stays on the Azure backbone (not public internet) and uses private IP addresses. VPN Gateway adds unnecessary overhead and cost for VNet-to-VNet connectivity. ExpressRoute connects on-premises networks, not VNet-to-VNet. NSG rules control traffic flow but don't establish connectivity between peered networks.",
    whyCorrect: "Global VNet peering is the simplest, lowest-latency method for cross-region VNet-to-VNet connectivity using private IPs — traffic transits Microsoft's global backbone.",
    whyIncorrect: {
      A: "VPN Gateway creates encrypted tunnels over public internet — useful for on-premises connectivity, but more expensive and higher latency than peering for VNet-to-VNet.",
      C: "ExpressRoute is for connecting on-premises infrastructure to Azure, not for VNet-to-VNet connectivity.",
      D: "NSG rules filter traffic but don't create network connectivity — without peering, VMs in separate VNets can't communicate regardless of NSG rules.",
    },
    references: [{ title: "Virtual Network Peering", url: "https://learn.microsoft.com/azure/virtual-network/virtual-network-peering-overview" }],
    grounding: { groundingScore: 0.95, citationCoverage: 0.91, retrievedDocumentIds: ["doc-az104-002"] },
    tags: ["Virtual Networking", "VNet Peering", "Azure Administrator"],
  },
  {
    questionId: "q-az104-003",
    exam: "AZ-104",
    objective: "Implement and Manage Storage",
    difficulty: "Medium",
    type: "YesNo",
    question: "Azure Blob Storage lifecycle management policies can automatically move blobs from Hot tier to Cool tier after a specified number of days since last modification.",
    correctAnswer: ["Yes"],
    explanation: "Azure Blob Storage lifecycle management policies allow automatic tiering of blobs based on age. You can configure rules to transition blobs from Hot → Cool → Cold → Archive tiers based on last modified date, last accessed date, or creation date. This reduces storage costs by automatically moving infrequently accessed data to cheaper tiers.",
    whyCorrect: "Lifecycle management policies are specifically designed for automated tier transitions based on blob age/access patterns — this is a core Azure storage cost optimization feature.",
    whyIncorrect: { No: "Lifecycle management policies explicitly support Hot-to-Cool transitions based on days since last modification." },
    references: [{ title: "Azure Blob Storage Lifecycle Management", url: "https://learn.microsoft.com/azure/storage/blobs/lifecycle-management-overview" }],
    grounding: { groundingScore: 0.97, citationCoverage: 0.94, retrievedDocumentIds: ["doc-az104-003"] },
    tags: ["Azure Storage", "Blob Storage", "Lifecycle Management"],
  },
  // GH-300 additional questions
  {
    questionId: "q-gh300-003",
    exam: "GH-300",
    objective: "Configure and Use Code Scanning",
    difficulty: "Medium",
    type: "MultipleChoiceSingle",
    question: "A development team wants to automatically scan their JavaScript codebase for security vulnerabilities on every pull request. Which GitHub Advanced Security feature and configuration should they use?",
    options: [
      { id: "A", text: "Enable secret scanning with custom patterns for the repository" },
      { id: "B", text: "Configure CodeQL analysis in a GitHub Actions workflow triggered on pull_request events" },
      { id: "C", text: "Set up Dependabot alerts with automatic security updates" },
      { id: "D", text: "Enable GitHub Advisory Database notifications for the repository" },
    ],
    correctAnswer: ["B"],
    explanation: "CodeQL is GitHub's semantic code analysis engine that identifies security vulnerabilities in source code. Configuring CodeQL in a GitHub Actions workflow triggered on `pull_request` events automatically scans code changes for vulnerabilities before merge. Secret scanning (A) finds secrets/credentials, not code vulnerabilities. Dependabot (C) handles dependency vulnerabilities, not code logic issues. Advisory Database (D) tracks known vulnerabilities in packages, not custom code.",
    whyCorrect: "CodeQL analysis triggered on pull_request is the correct pattern for automated code vulnerability scanning on every PR — it analyzes code logic and data flow for security issues.",
    whyIncorrect: {
      A: "Secret scanning detects leaked credentials, API keys, and tokens — not code logic vulnerabilities.",
      C: "Dependabot scans dependencies (npm packages, etc.) for known CVEs, not custom application code.",
      D: "The Advisory Database is a reference database for known vulnerabilities; it doesn't actively scan code.",
    },
    references: [{ title: "CodeQL Code Scanning", url: "https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql" }],
    grounding: { groundingScore: 0.95, citationCoverage: 0.91, retrievedDocumentIds: ["doc-gh300-003"] },
    tags: ["Code Scanning", "CodeQL", "GitHub Advanced Security"],
  },
  {
    questionId: "q-gh300-004",
    exam: "GH-300",
    objective: "Configure and Use Secret Scanning",
    difficulty: "Medium",
    type: "MultipleChoiceSingle",
    question: "A team wants to prevent developers from accidentally pushing API keys to GitHub. They want the push to be rejected before it reaches the repository. Which GitHub Advanced Security feature provides this?",
    options: [
      { id: "A", text: "Secret scanning alerts — notifies after a secret is pushed" },
      { id: "B", text: "Push protection — blocks pushes containing detected secrets before they're written to the repository" },
      { id: "C", text: "Dependabot security updates — monitors dependencies for exposed credentials" },
      { id: "D", text: "Code scanning with CodeQL — analyzes code for hardcoded secrets" },
    ],
    correctAnswer: ["B"],
    explanation: "Push protection is a GitHub Advanced Security feature that intercepts pushes containing detected secrets BEFORE they're written to the repository. When a push containing a known secret pattern is detected, GitHub blocks the push and notifies the developer. This is fundamentally different from secret scanning alerts (A) which notify AFTER the secret is already in the repository.",
    whyCorrect: "Push protection operates as a pre-receive hook — it blocks the push before any data is written, preventing the secret from ever entering git history.",
    whyIncorrect: {
      A: "Secret scanning alerts are reactive — they detect secrets already in the repository and notify owners, but the secret has already been committed.",
      C: "Dependabot monitors for known vulnerabilities in package dependencies, not credential exposure.",
      D: "CodeQL analyzes code logic for security vulnerabilities; it's not optimized for detecting secret patterns compared to secret scanning.",
    },
    references: [{ title: "Push Protection for Secret Scanning", url: "https://docs.github.com/en/code-security/secret-scanning/push-protection-for-repositories-and-organizations" }],
    grounding: { groundingScore: 0.96, citationCoverage: 0.93, retrievedDocumentIds: ["doc-gh300-004"] },
    tags: ["Push Protection", "Secret Scanning", "GitHub Advanced Security"],
  },
];

export function getMockSession(examCode: string, mode: ExamMode, count: number): import("@/types/exam").ExamSession {
  const blueprint = EXAM_BLUEPRINTS[examCode];
  const examQuestions = MOCK_QUESTIONS.filter((q) => q.exam === examCode);

  // Cycle through available questions to always deliver exactly `count` items.
  // Repeated questions get a unique questionId suffix so the store tracks them separately.
  const questions: Question[] = [];
  if (examQuestions.length > 0) {
    for (let i = 0; i < count; i++) {
      const base = examQuestions[i % examQuestions.length];
      const cycle = Math.floor(i / examQuestions.length);
      questions.push(cycle === 0 ? base : { ...base, questionId: `${base.questionId}-r${cycle}` });
    }
  }

  return {
    sessionId: `session-${Date.now()}`,
    examCode,
    mode,
    startedAt: new Date().toISOString(),
    durationMinutes: blueprint?.durationMinutes ?? 100,
    questions,
    answers: {},
    markedForReview: [],
    currentQuestionIndex: 0,
    submitted: false,
  };
}
